services:

  imagemagick:
    platform: linux/amd64
    command: /root/build.sh
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/output

  imagemagick-clang17:
    platform: linux/amd64
    command: /root/build.sh
    build:
      context: .
      dockerfile: Dockerfile-clang17
    volumes:
      - .:/output

  imagemagick-clang18:
    platform: linux/amd64
    command: /root/build.sh
    build:
      context: .
      dockerfile: Dockerfile-clang18
    volumes:
      - .:/output
