
name: Check any R package at an URL

on:
  workflow_dispatch:
    inputs:
      inpurl:
        description: 'URL to a source R package'
        required: true
        type: string
      inpcont:
        description: 'Check container'
        required: true
        type: choice
        options:
        - 'atlas'
        - 'centos7'
        - 'clang-asan'
        - 'clang16'
        - 'gcc13'
        - 'nold'
        - 'ubuntu-clang'
        - 'ubuntu-gcc12'
        - 'ubuntu-next'
        - 'ubuntu-release'
      inprver:
        description: 'R version (for containers with multiple R versions)'
        required: false
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check with ${{ github.event.inputs.inpcont }}
    container:
      image: ghcr.io/r-hub/containers/${{ github.event.inputs.inpcont }}:latest

    steps:
    - name: Download package
      run: |
        mkdir /check
        cd /check
        curl -LO "${{ github.event.inputs.inpurl }}"

    - name: Install dependencies and check package
      run: r-check
      env:
        R_VERSION: ${{ github.event.inputs.inprver }}

    - name: Upload check result as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: check-results
        path: /check
